#!/usr/bin/env python3
# SPDX-License-Identifier: MulanPSL-2.0
"""D1 dexterous-hand primitive — Linker 6-axis hand over CAN, direct (non-ROS).

Owns the joint-level robonix/primitive/hand/* contracts, served over gRPC:

  robonix/primitive/hand/driver                   rpc   lifecycle (via on_init)
  robonix/primitive/hand/info                     rpc   axis layout (JointInfo[])
  robonix/primitive/hand/move_joint               rpc   set axis positions by name
  robonix/primitive/hand/set_joint_speed_limits   rpc   per-axis speed limit by name
  robonix/primitive/hand/set_joint_torque_limits  rpc   per-axis torque limit by name
  robonix/primitive/hand/get_state                rpc   read current axis positions [0,1]

Wraps beingbeyond_d1_sdk.dex_hand.DexHand directly. All values are normalized
[0,1]; for position 1=closed/0=open, for speed/torque 1=max/0=min. The hand has
6 control axes (see _AXES), each self-describing via info.

State readback uses the get_state rpc (the D1 deploy has no ROS backend, so the
state_joint / state_finger topic_out streams are not served; get_state is the
axis-level on-demand equivalent).

Not provided: state_joint / state_finger (topic_out — need a ROS backend the D1
deploy does not run) and the finger-level move_finger / set_finger_* contracts
(the joint interface fully controls this 6-axis hand; info carries finger+type).
"""
from __future__ import annotations

import math
import os
import threading

from robonix_api import Primitive, Ok, Err

d1_hand = Primitive(id="d1_hand", namespace="robonix/primitive/hand")

# codegen products (generated by scripts/build.sh into rbnx-build/codegen/
# proto_gen, auto-added to sys.path by the Primitive constructor).
import hand_pb2  # type: ignore[import-not-found]  # noqa: E402

# Control-axis layout, in DexHand.joint_names / hardware order (index 0..5).
# (name, finger, type, joint_index, description). Endpoint semantics follow
# JointInfo.msg: bend 0=extended/1=flexed, oppose 0=neutral/1=full opposition.
_AXES = [
    ("thumb_cmc_pitch",  "thumb",  "bend",   0, "拇指掌指关节屈曲：0=伸直, 1=屈曲"),
    ("thumb_cmc_yaw",    "thumb",  "oppose", 0, "拇指对掌/侧摆：0=中立, 1=完全对掌"),
    ("index_mcp_pitch",  "index",  "bend",   0, "食指掌指关节屈曲：0=伸直, 1=屈曲"),
    ("middle_mcp_pitch", "middle", "bend",   0, "中指掌指关节屈曲：0=伸直, 1=屈曲"),
    ("ring_mcp_pitch",   "ring",   "bend",   0, "无名指掌指关节屈曲：0=伸直, 1=屈曲"),
    ("pinky_mcp_pitch",  "pinky",  "bend",   0, "小指掌指关节屈曲：0=伸直, 1=屈曲"),
]
_NAMES = [a[0] for a in _AXES]
_NAME2IDX = {name: i for i, name in enumerate(_NAMES)}
_NUM = len(_AXES)

# ── shared state ──────────────────────────────────────────────────────────────
_hand = None
_lock = threading.Lock()
# Last commanded position target (6-vector, [0,1]); "unlisted axes hold their
# current target" is implemented by overlaying onto this.
_targets = [0.0] * _NUM


# ── helpers ───────────────────────────────────────────────────────────────────
def _overlay(base, items):
    """Overlay `items` (repeated {name, value}) onto a copy of `base` (6-vector),
    addressing axes by name. Returns (new_vector, None) or (None, error_message).
    Rejects — never clamps — per the move_joint/set_*_limits contract:
    empty request, unknown name, duplicate name, non-finite or out-of-[0,1] value.
    """
    if len(items) == 0:
        return None, "empty request: no axes listed"
    out = list(base)
    seen = set()
    for it in items:
        name = it.name
        val = it.value
        if name not in _NAME2IDX:
            return None, f"unknown axis name: {name!r} (known: {_NAMES})"
        if name in seen:
            return None, f"duplicate axis name: {name!r}"
        seen.add(name)
        if not math.isfinite(val) or val < 0.0 or val > 1.0:
            return None, f"value out of range [0,1] for {name!r}: {val}"
        out[_NAME2IDX[name]] = float(val)
    return out, None


# ── gRPC handlers ─────────────────────────────────────────────────────────────
@d1_hand.grpc("robonix/primitive/hand/info")
def info(request, context):
    """Query the hand's control-axis layout (6 axes, self-describing).
    Contract: robonix/primitive/hand/info."""
    _ = request, context
    if _hand is None:
        return hand_pb2.GetHandInfo_Response(
            ok=False, message="hand not initialized — Driver(CMD_INIT) failed or never ran"
        )
    joints = [
        hand_pb2.JointInfo(
            finger=finger, type=typ, joint_index=ji, name=name, description=desc
        )
        for (name, finger, typ, ji, desc) in _AXES
    ]
    return hand_pb2.GetHandInfo_Response(ok=True, message="", joints=joints)


@d1_hand.grpc("robonix/primitive/hand/move_joint")
def move_joint(request, context):
    """Set control-axis positions by name (normalized [0,1], 1=closed). Only
    listed axes move; unlisted hold their last target. Rejects (never clamps)
    empty/unknown/duplicate/out-of-range. ok=true = accepted & dispatched, NOT
    reached. Contract: robonix/primitive/hand/move_joint."""
    _ = context
    with _lock:
        hand = _hand
        if hand is None:
            return hand_pb2.MoveJoint_Response(ok=False, message="hand not initialized")
        new, err = _overlay(_targets, request.targets)
        if err:
            return hand_pb2.MoveJoint_Response(ok=False, message=err)
        try:
            hand.set_joint_pos(new)
        except Exception as exc:  # noqa: BLE001
            return hand_pb2.MoveJoint_Response(ok=False, message=f"set_joint_pos failed: {exc}")
        _targets[:] = new
    return hand_pb2.MoveJoint_Response(ok=True, message="")


@d1_hand.grpc("robonix/primitive/hand/set_joint_speed_limits")
def set_joint_speed_limits(request, context):
    """Set per-axis speed limit by name (normalized [0,1], 1=fastest). Only
    listed axes updated. Contract: robonix/primitive/hand/set_joint_speed_limits."""
    _ = context
    with _lock:
        hand = _hand
        if hand is None:
            return hand_pb2.SetJointSpeedLimits_Response(ok=False, message="hand not initialized")
        try:
            cur = hand.get_speed()
        except Exception as exc:  # noqa: BLE001
            return hand_pb2.SetJointSpeedLimits_Response(ok=False, message=f"read speed failed: {exc}")
        new, err = _overlay(cur, request.limits)
        if err:
            return hand_pb2.SetJointSpeedLimits_Response(ok=False, message=err)
        try:
            hand.set_speed(new)
        except Exception as exc:  # noqa: BLE001
            return hand_pb2.SetJointSpeedLimits_Response(ok=False, message=f"set_speed failed: {exc}")
    return hand_pb2.SetJointSpeedLimits_Response(ok=True, message="")


@d1_hand.grpc("robonix/primitive/hand/set_joint_torque_limits")
def set_joint_torque_limits(request, context):
    """Set per-axis torque limit by name (normalized [0,1], 1=max). Only listed
    axes updated. Contract: robonix/primitive/hand/set_joint_torque_limits."""
    _ = context
    with _lock:
        hand = _hand
        if hand is None:
            return hand_pb2.SetJointTorqueLimits_Response(ok=False, message="hand not initialized")
        try:
            cur = hand.get_torque()
        except Exception as exc:  # noqa: BLE001
            return hand_pb2.SetJointTorqueLimits_Response(ok=False, message=f"read torque failed: {exc}")
        new, err = _overlay(cur, request.limits)
        if err:
            return hand_pb2.SetJointTorqueLimits_Response(ok=False, message=err)
        try:
            hand.set_torque(new)
        except Exception as exc:  # noqa: BLE001
            return hand_pb2.SetJointTorqueLimits_Response(ok=False, message=f"set_torque failed: {exc}")
    return hand_pb2.SetJointTorqueLimits_Response(ok=True, message="")


@d1_hand.grpc("robonix/primitive/hand/get_state")
def get_state(request, context):
    """Read current control-axis positions (normalized [0,1], 1=closed), in
    info's axis order. Contract: robonix/primitive/hand/get_state."""
    _ = request, context
    with _lock:
        hand = _hand
        if hand is None:
            return hand_pb2.GetJointState_Response(ok=False, message="hand not initialized")
        try:
            pos = hand.read_joint_pos()
        except Exception as exc:  # noqa: BLE001
            return hand_pb2.GetJointState_Response(ok=False, message=f"read state failed: {exc}")
    return hand_pb2.GetJointState_Response(
        ok=True, message="", positions=[float(v) for v in pos[:_NUM]]
    )


# ── lifecycle ─────────────────────────────────────────────────────────────────
@d1_hand.on_init
def init(cfg):
    """Open the DexHand over CAN and seed the position-target cache from the
    current pose. Config keys (fall back to D1_HAND_* env): hand_type
    (right|left), can_iface, baudrate."""
    global _hand
    cfg = cfg or {}
    hand_type = str(cfg.get("hand_type") or os.environ.get("D1_HAND_TYPE", "right"))
    can_iface = str(cfg.get("can_iface") or os.environ.get("D1_HAND_CAN", "can0"))
    baudrate = int(cfg.get("baudrate") or os.environ.get("D1_HAND_BAUD", "1000000"))

    try:
        from beingbeyond_d1_sdk.dex_hand import DexHand
    except Exception as exc:  # noqa: BLE001
        return Err(f"import beingbeyond_d1_sdk.dex_hand failed: {exc}")

    try:
        hand = DexHand(hand_type=hand_type, can_iface=can_iface, baudrate=baudrate)
        cur = hand.read_joint_pos()
    except Exception as exc:  # noqa: BLE001
        return Err(f"open DexHand (type={hand_type}, can={can_iface}) failed: {exc}")

    with _lock:
        _hand = hand
        _targets[:] = list(cur)[:_NUM] + [0.0] * max(0, _NUM - len(cur))
    print(f"[d1_hand] ready: type={hand_type} can={can_iface} axes={_NUM}", flush=True)
    return Ok()


@d1_hand.on_shutdown
def shutdown():
    """Open the hand (safe pose) and release the CAN interface."""
    global _hand
    with _lock:
        hand, _hand = _hand, None
    if hand is not None:
        try:
            hand.open_hand()
        except Exception:  # noqa: BLE001
            pass
        try:
            hand.close_can()
        except Exception:  # noqa: BLE001
            pass
    return Ok()


def main() -> int:
    d1_hand.run()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
